# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendAzureRmResourceGroupName: 'rg'
    backendAzureRmStorageAccountName: 'myterrstroage'
    backendAzureRmContainerName: 'terracontainer'
    backendAzureRmKey: 'terraform.state'
- task: TerraformTaskV4@4
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Free Trial(1)(f855b573-cd07-43fa-b1c9-4e1ed6028799)'
  inputs:
    provider: 'azurerm'
    command: 'validate'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'